spring.application.name=gulix-api

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
refresh-token.expiration=${REFRESH_TOKEN_EXPIRATION}
stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}
open.route.service.key=${OPEN_ROUTE_SERVICE_KEY}


gulix.estabelecimento.latitude=-23.550520
gulix.estabelecimento.longitude=-46.633308